[package]
name = "concord_core"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
reqwest = { workspace = true, features = ["rustls-native-certs", "http2"] }
http.workspace = true
bytes.workspace = true
serde = { workspace = true, optional = true, features = ["derive"] }
serde_json = { workspace = true, optional = true }
base64.workspace = true
thiserror.workspace = true
url.workspace = true
urlencoding.workspace = true


[features]
json = ["dep:serde", "dep:serde_json", "reqwest/json"]
gzip = ["reqwest/gzip"]
brotli = ["reqwest/brotli"]
deflate = ["reqwest/deflate"]
cookies = ["reqwest/cookies"]
multipart = ["reqwest/multipart"]